# Rôle : Déclare toutes les routes disponibles dans l'application.
# Fonctionnement :
# Liste les chemins (URI) associés à des méthodes HTTP (GET, POST, etc.).
# Associe chaque route à une "action" dans un contrôleur (ex. : Metroid\Controller\IndexAction).

routes:
  # Page d'accueil :
  "/":
    method: GET
    callable: App\Controller\HomeController::index

  # Page Nos livres à l'échange :
  "/books":
    method: GET
    callable: App\Controller\BookController::listAll

  # Affichage d'un livre
  "/books/:id":
    method: GET
    callable: App\Controller\BookController::show

  # Formulaire d'inscription
  "/auth/registration":
    method: GET|POST
    callable: App\Controller\AuthController::register

  # Formulaire de connexion
  "/auth/login":
    method: GET|POST
    callable: App\Controller\AuthController::login

  # Deconnexion
  "/auth/logout":
    method: GET
    callable: App\Controller\AuthController::logout

  # Profil utilisateur public
  "/user/:id":
    method: GET
    callable: App\Controller\AccountController::publicProfile

  # Page Mon Compte
  "/account":
    method: GET
    callable: App\Controller\AccountController::show

  # Mise à jour du profil
  "/account/update":
    method: POST
    callable: App\Controller\AccountController::update

  # Création d'un livre
  "/account/book/create":
    callable: App\Controller\BookController::create
    method: POST

  # Edition d'un livre
  "/account/book/edit/:id":
    method: GET|POST
    callable: App\Controller\BookController::edit

  # Suppression d'un livre
  "/account/book/delete/:id":
    method: POST
    callable: App\Controller\BookController::delete

  # Nouvelle conversation ou affichage de la conversation
  "/message/new":
    method: GET
    callable: App\Controller\MessageController::startNewConversation

  # Page principale : Affiche la liste des threads
  "/thread":
    method: GET
    callable: App\Controller\MessageController::index

  # Affichage des messages d’un thread ou envoi d’un nouveau message
  /thread/:threadId/messages:
    method: GET|POST
    callable: App\Controller\MessageController::threadMessages

  # Suppression d’un message (appel AJAX POST)
  # Method : DELETE
  "/message/:messageId":
    method: DELETE
    callable: App\Controller\MessageController::delete

  # Pour la modification utiliser PUT (toutes les données) ou PATCH (update partiel)
  # Si on utilise Patch, ppur la JsonResponse, il faudra application/merge-patch+json
