# Rôle : Déclare toutes les routes disponibles dans l'application.
# Fonctionnement :
# Liste les chemins (URI) associés à des méthodes HTTP (GET, POST, etc.).
# Associe chaque route à une "action" dans un contrôleur (ex. : Metroid\Controller\IndexAction).

routes:
  # Page d'accueil :
  "/":
    method: GET
    callable: App\Controller\HomeController::index

  # Page Nos livres à l'échange :
  "/books":
    method: GET
    callable: App\Controller\BookController::listAll

  # Affichage d'un livre
  "/books/:id":
    method: GET
    callable: App\Controller\BookController::show

  # Formulaire d'inscription
  "/auth/registration":
    method: GET|POST
    callable: App\Controller\AuthController::register

  # Formulaire de connexion
  "/auth/login":
    method: GET|POST
    callable: App\Controller\AuthController::login

  # Deconnexion
  "/auth/logout":
    method: GET
    callable: App\Controller\AuthController::logout

  # Page Mon Compte
  "/account":
    method: GET
    callable: App\Controller\AccountController::show

  # Mise à jour du profil
  "/account/update":
    method: POST
    callable: App\Controller\AccountController::update

  # Création d'un livre
  "/account/book/create":
    callable: App\Controller\BookController::create
    method: POST

  # Edition d'un livre
  "/account/book/edit/:id":
    method: GET|POST
    callable: App\Controller\BookController::edit

  # Suppression d'un livre
  "/account/book/delete/:id":
    method: POST
    callable: App\Controller\BookController::delete
