<!--
    Template "Inscription utilisateur"
    ==================================
    Cette page permet à un nouvel utilisateur de :
    - S’inscrire en remplissant un formulaire avec un nom, une adresse email et un mot de passe
    - Être redirigé vers la page de connexion s’il possède déjà un compte
-->
<section class="register-container">
    <div class="register-left">
        <h1>Inscription</h1>

        <form action="<?= $this->url('auth/registration') ?>" method="POST" class="form">
            <label for="name">Nom d'utilisateur</label>
            <input type="text" id="name" name="name" required>

            <label for="email">Adresse email</label>
            <input type="email" id="email" name="email" required>

            <label for="password">Mot de passe</label>
            <input type="password" id="password" name="password" required>

            <button type="submit" class="btn-green">S’inscrire</button>
        </form>

        <p class="register-alt">Déjà inscrit ? <a href="<?= $this->url('auth/login') ?>">Connectez-vous</a></p>
    </div>

    <div class="register-right">
        <img src="<?= IMG_PATH . 'library.jpg' ?>" alt="Photo d'étagères de livres">
        <p class="photo-credit">Hamza</p>
    </div>
</section>